---
- hosts: elk
  tasks:
    - copy: src=/v/elk/elasticsearch.repo dest=/etc/yum.repos.d/elasticsearch.repo mode=0755 force=no

    - yum: name=java-1.8.0-openjdk state=present update_cache=yes
    - yum: name=epel-release state=present update_cache=yes
    - yum: name=elasticsearch state=present update_cache=yes
    - yum: name=git state=present update_cache=yes
    - service: name=elasticsearch state=started enabled=yes

    - shell: if grep TetraNoodles /etc/elasticsearch/elasticsearch.yml; then echo 'elasticsearch.yml is up-to-date'; else rm -fr /etc/elasticsearch/elasticsearch.yml; fi
    - copy: src=/v/elk/elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml mode=0755 force=no
