---
- hosts: node1, node2
  become: true 
  tasks:
    # ADD ElasticSearch Repositories
    - copy: src=/v/elk/elasticsearch.repo dest=/etc/yum.repos.d/elasticsearch.repo mode=0755 force=no

    - yum: name={{item}} state=present update_cache=yes
      with_items:
       - java-1.8.0-openjdk 
       - nmap 
       - epel-release
       - elasticsearch 
       - git 
    
    - service: name=elasticsearch state=started enabled=yes
    # REMOVE elasticsearch.yml if it's not up-to-date (e.g. the first time you run playbook it'll customize defaults)
    - shell: if grep TetraNoodles /etc/elasticsearch/elasticsearch.yml; then echo 'elasticsearch.yml is up-to-date'; else rm -fr /etc/elasticsearch/elasticsearch.yml; fi
    - copy: src=/v/elk/elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml mode=0755 force=no
      notify:
      - restart elasticsearch 

  handlers:
    - name: restart elasticsearch
      service: name=elasticsearch state=restarted 

- hosts: node2
  become: true
  tasks:
    - set_fact: colon=":"
    - lineinfile: dest=/etc/elasticsearch/elasticsearch.yml regexp=' node.name{{colon}} Tetra_search_1' line=' node.name{{colon}} Tetra_search_2' state=present 
    - lineinfile: dest=/etc/elasticsearch/elasticsearch.yml regexp=' network.host{{colon}} 192.168.0.34' line=' network.host{{colon}} 192.168.0.35' state=present 

